/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductInstanceModel } from '../../models/product-instance-model';

export interface CreateInstance$Params {
  identifier?: string;
  revision?: number;
  save?: boolean;
}

export function createInstance(http: HttpClient, rootUrl: string, params?: CreateInstance$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductInstanceModel>> {
  const rb = new RequestBuilder(rootUrl, createInstance.PATH, 'post');
  if (params) {
    rb.query('identifier', params.identifier, {});
    rb.query('revision', params.revision, {});
    rb.query('save', params.save, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductInstanceModel>;
    })
  );
}

createInstance.PATH = '/api/moryx/products/instances';

