//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Moryx.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string JoinWorkplanStep_Description {
            get {
                return ResourceManager.GetString("JoinWorkplanStep_Description", resourceCulture);
            }
        }
        
        public static string JoinWorkplanStep_Name {
            get {
                return ResourceManager.GetString("JoinWorkplanStep_Name", resourceCulture);
            }
        }
        
        public static string SplitWorkplanStep_Description {
            get {
                return ResourceManager.GetString("SplitWorkplanStep_Description", resourceCulture);
            }
        }
        
        public static string SplitWorkplanStep_Name {
            get {
                return ResourceManager.GetString("SplitWorkplanStep_Name", resourceCulture);
            }
        }
        
        public static string SubworkplanStep_Description {
            get {
                return ResourceManager.GetString("SubworkplanStep_Description", resourceCulture);
            }
        }
        
        public static string SubworkplanStep_DisplayName {
            get {
                return ResourceManager.GetString("SubworkplanStep_DisplayName", resourceCulture);
            }
        }
    }
}
