/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EntryValidation {
  isRequired?: boolean;
  maximum?: number;
  minimum?: number;
  regex?: string | null;
}
