/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductModel as MoryxAbstractionLayerProductsEndpointsProductModel } from '../../models/Moryx/AbstractionLayer/Products/Endpoints/product-model';

export interface GetTypeByIdentity$Params {
  identity?: string;
}

export function getTypeByIdentity(http: HttpClient, rootUrl: string, params?: GetTypeByIdentity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MoryxAbstractionLayerProductsEndpointsProductModel>>> {
  const rb = new RequestBuilder(rootUrl, getTypeByIdentity.PATH, 'get');
  if (params) {
    rb.query('identity', params.identity, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MoryxAbstractionLayerProductsEndpointsProductModel>>;
    })
  );
}

getTypeByIdentity.PATH = '/api/moryx/products/types';
