//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Launcher.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Moryx.Launcher.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_Company {
            get {
                return ResourceManager.GetString("AboutModal_Misc_Company", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_Configuration {
            get {
                return ResourceManager.GetString("AboutModal_Misc_Configuration", resourceCulture);
            }
        }
        
        public static string AboutModal_Copyright {
            get {
                return ResourceManager.GetString("AboutModal_Copyright", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_Description {
            get {
                return ResourceManager.GetString("AboutModal_Misc_Description", resourceCulture);
            }
        }
        
        public static string Layout_Details {
            get {
                return ResourceManager.GetString("Layout_Details", resourceCulture);
            }
        }
        
        public static string Layout_ExitFullscreen {
            get {
                return ResourceManager.GetString("Layout_ExitFullscreen", resourceCulture);
            }
        }
        
        public static string Layout_FullscreenMode {
            get {
                return ResourceManager.GetString("Layout_FullscreenMode", resourceCulture);
            }
        }
        
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        public static string Layout_Language {
            get {
                return ResourceManager.GetString("Layout_Language", resourceCulture);
            }
        }
        
        public static string Layout_Modules {
            get {
                return ResourceManager.GetString("Layout_Modules", resourceCulture);
            }
        }
        
        public static string Layout_More {
            get {
                return ResourceManager.GetString("Layout_More", resourceCulture);
            }
        }
        
        public static string Layout_OperatorMode {
            get {
                return ResourceManager.GetString("Layout_OperatorMode", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_Product {
            get {
                return ResourceManager.GetString("AboutModal_Misc_Product", resourceCulture);
            }
        }
        
        public static string Layout_Search {
            get {
                return ResourceManager.GetString("Layout_Search", resourceCulture);
            }
        }
        
        public static string SETTING_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTING_LANGUAGE", resourceCulture);
            }
        }
        
        public static string Layout_SignIn {
            get {
                return ResourceManager.GetString("Layout_SignIn", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_TargetFramework {
            get {
                return ResourceManager.GetString("AboutModal_Misc_TargetFramework", resourceCulture);
            }
        }
        
        public static string AboutModal_Misc_Title {
            get {
                return ResourceManager.GetString("AboutModal_Misc_Title", resourceCulture);
            }
        }
        
        public static string TRADEMARK {
            get {
                return ResourceManager.GetString("TRADEMARK", resourceCulture);
            }
        }
        
        public static string AboutModal_Version {
            get {
                return ResourceManager.GetString("AboutModal_Version", resourceCulture);
            }
        }
        
        public static string Layout_Views {
            get {
                return ResourceManager.GetString("Layout_Views", resourceCulture);
            }
        }
    }
}
