<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Moryx.Material\Moryx.Material.csproj" />
    <ProjectReference Include="..\..\Moryx.Material.Integrations.Orders\Moryx.Material.Integrations.Orders.csproj" />
    <ProjectReference Include="..\..\Moryx.Material.Integrations.Orders.Integrator\Moryx.Material.Integrations.Orders.Integrator.csproj" />
    <ProjectReference Include="..\..\Moryx.Orders\Moryx.Orders.csproj" />
    <ProjectReference Include="..\..\Moryx.TestTools.IntegrationTest\Moryx.TestTools.IntegrationTest.csproj" />
  </ItemGroup>

</Project>
