/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VariantDescriptor } from '../../models/variant-descriptor';

export interface GetVariant$Params {
  guid: string;
  variantName: string;
}

export function getVariant(http: HttpClient, rootUrl: string, params: GetVariant$Params, context?: HttpContext): Observable<StrictHttpResponse<VariantDescriptor>> {
  const rb = new RequestBuilder(rootUrl, getVariant.PATH, 'get');
  if (params) {
    rb.path('guid', params.guid, {});
    rb.path('variantName', params.variantName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VariantDescriptor>;
    })
  );
}

getVariant.PATH = '/api/moryx/media/{guid}/{variantName}';

