/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdviceModel {
  amount?: number;
  partId?: number | null;
  toteBoxNumber?: string | null;
}

