/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomAttributeData } from '../models/custom-attribute-data';
import { EventAttributes } from '../models/event-attributes';
import { MemberTypes } from '../models/member-types';
import { MethodInfo } from '../models/method-info';
import { Module } from '../models/module';
import { Type } from '../models/type';
export interface EventInfo {
  addMethod?: MethodInfo;
  attributes?: EventAttributes;
  customAttributes?: Array<CustomAttributeData> | null;
  declaringType?: Type;
  eventHandlerType?: Type;
  isCollectible?: boolean;
  isMulticast?: boolean;
  isSpecialName?: boolean;
  memberType?: MemberTypes;
  metadataToken?: number;
  module?: Module;
  name?: string | null;
  raiseMethod?: MethodInfo;
  reflectedType?: Type;
  removeMethod?: MethodInfo;
}
