/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum LogLevel {
  Trace = 'Trace',
  Debug = 'Debug',
  Information = 'Information',
  Warning = 'Warning',
  Error = 'Error',
  Critical = 'Critical',
  None = 'None'
}
