/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SetupJobClassification } from '../models/setup-job-classification';
import { SetupStepModel } from '../models/setup-step-model';
export interface SetupJobModel {
  classification?: SetupJobClassification;
  steps?: Array<SetupStepModel> | null;
  targetRecipeId?: number;
}
