/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface VisualizationModel {
  category?: Category;
  icon?: string | null;
}
