/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetContainers$Params as GetContainers$Params } from './fn/material-management/get-containers';
export { getContainers as getContainers } from './fn/material-management/get-containers';
export type { GetTypes$Params as GetTypes$Params } from './fn/material-management/get-types';
export { getTypes as getTypes } from './fn/material-management/get-types';
export type { PreAdviceAsync$Params as PreAdviceAsync$Params } from './fn/material-management/pre-advice-async';
export { preAdviceAsync as preAdviceAsync } from './fn/material-management/pre-advice-async';
export type { Deregister$Params as Deregister$Params } from './fn/material-management/deregister';
export { deregister as deregister } from './fn/material-management/deregister';
export type { ContainerChanges$Params as ContainerChanges$Params } from './fn/material-management/container-changes';
export { containerChanges as containerChanges } from './fn/material-management/container-changes';
export type { HasOrderIntegration$Params as HasOrderIntegration$Params } from './fn/material-management/has-order-integration';
export { hasOrderIntegration as hasOrderIntegration } from './fn/material-management/has-order-integration';
export type { GetOrderReferences$Params as GetOrderReferences$Params } from './fn/material-management/get-order-references';
export { getOrderReferences as getOrderReferences } from './fn/material-management/get-order-references';
export type { GetTypeTree$Params as GetTypeTree$Params } from './fn/resource-modification/get-type-tree';
export { getTypeTree as getTypeTree } from './fn/resource-modification/get-type-tree';
export type { GetType$Params as GetType$Params } from './fn/resource-modification/get-type';
export { getType as getType } from './fn/resource-modification/get-type';
export type { GetDetailsBatch$Params as GetDetailsBatch$Params } from './fn/resource-modification/get-details-batch';
export { getDetailsBatch as getDetailsBatch } from './fn/resource-modification/get-details-batch';
export type { Save$Params as Save$Params } from './fn/resource-modification/save';
export { save as save } from './fn/resource-modification/save';
export type { GetResources$Params as GetResources$Params } from './fn/resource-modification/get-resources';
export { getResources as getResources } from './fn/resource-modification/get-resources';
export type { GetDetails$Params as GetDetails$Params } from './fn/resource-modification/get-details';
export { getDetails as getDetails } from './fn/resource-modification/get-details';
export type { Update$Params as Update$Params } from './fn/resource-modification/update';
export { update as update } from './fn/resource-modification/update';
export type { Remove$Params as Remove$Params } from './fn/resource-modification/remove';
export { remove as remove } from './fn/resource-modification/remove';
export type { InvokeMethod$Params as InvokeMethod$Params } from './fn/resource-modification/invoke-method';
export { invokeMethod as invokeMethod } from './fn/resource-modification/invoke-method';
export type { ConstructWithParameters$Params as ConstructWithParameters$Params } from './fn/resource-modification/construct-with-parameters';
export { constructWithParameters as constructWithParameters } from './fn/resource-modification/construct-with-parameters';
