// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moryx.Operators.Management.Model;

#nullable disable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Moryx.Operators.Management.Model.Migrations.Sqlite;

[DbContext(typeof(SqliteOperatorsContext))]
[Migration("20240808095012_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "6.0.32");

        modelBuilder.Entity("Moryx.Operators.Management.Model.OperatorEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Created")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("Deleted")
                    .HasColumnType("TEXT");

                b.Property<string>("FirstName")
                    .HasColumnType("TEXT");

                b.Property<string>("Identifier")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("LastName")
                    .HasColumnType("TEXT");

                b.Property<string>("Pseudonym")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Updated")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("OperatorEntities", "public");
            });

        modelBuilder.Entity("Moryx.Operators.Management.Model.ResourceLinkEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<long?>("OperatorEntityId")
                    .HasColumnType("INTEGER");

                b.Property<long>("ResourceId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("OperatorEntityId");

                b.ToTable("ResourceLinkEntities", "public");
            });

        modelBuilder.Entity("Moryx.Operators.Management.SkillEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Created")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("Deleted")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("Expiration")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("ObtainedOn")
                    .HasColumnType("TEXT");

                b.Property<string>("OperatorIdentifier")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("SkillTypeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Updated")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("SkillTypeId");

                b.ToTable("SkillEntities", "public");
            });

        modelBuilder.Entity("Moryx.Operators.Management.SkillTypeEntity", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CapabilitiesData")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("CapabilitiesType")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Created")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("Deleted")
                    .HasColumnType("TEXT");

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Updated")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("SkillTypeEntities", "public");
            });

        modelBuilder.Entity("Moryx.Operators.Management.Model.ResourceLinkEntity", b =>
            {
                b.HasOne("Moryx.Operators.Management.Model.OperatorEntity", null)
                    .WithMany("AssignedResources")
                    .HasForeignKey("OperatorEntityId");
            });

        modelBuilder.Entity("Moryx.Operators.Management.SkillEntity", b =>
            {
                b.HasOne("Moryx.Operators.Management.SkillTypeEntity", "SkillType")
                    .WithMany()
                    .HasForeignKey("SkillTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("SkillType");
            });

        modelBuilder.Entity("Moryx.Operators.Management.Model.OperatorEntity", b =>
            {
                b.Navigation("AssignedResources");
            });
#pragma warning restore 612, 618
    }
}
