<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
	  <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Moryx.Drivers.OpcUa\Moryx.Drivers.OpcUa.csproj" />
  </ItemGroup>

</Project>
