//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Drivers.Mqtt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.Drivers.Mqtt.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host address.
        /// </summary>
        public static string MqttDriver_BrokerUrl {
            get {
                return ResourceManager.GetString("MqttDriver_BrokerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host address of the mqtt broker.
        /// </summary>
        public static string MqttDriver_BrokerUrl_Description {
            get {
                return ResourceManager.GetString("MqttDriver_BrokerUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A driver for connecting to MQTT resources.
        /// </summary>
        public static string MqttDriver_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Broker.
        /// </summary>
        public static string MqttDriver_DisplayName {
            get {
                return ResourceManager.GetString("MqttDriver_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the MQTT driver.
        /// </summary>
        public static string MqttDriver_DriverState {
            get {
                return ResourceManager.GetString("MqttDriver_DriverState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has last will.
        /// </summary>
        public static string MqttDriver_HasLastWill {
            get {
                return ResourceManager.GetString("MqttDriver_HasLastWill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decides if a last will message should be registered on the broker.
        /// </summary>
        public static string MqttDriver_HasLastWill_Description {
            get {
                return ResourceManager.GetString("MqttDriver_HasLastWill_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root MQTT topic.
        /// </summary>
        public static string MqttDriver_Identifier {
            get {
                return ResourceManager.GetString("MqttDriver_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last will topic.
        /// </summary>
        public static string MqttDriver_LastWillTopic {
            get {
                return ResourceManager.GetString("MqttDriver_LastWillTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The topic the last will message should be published to. Has no effect if HasLastWill is not set.
        /// </summary>
        public static string MqttDriver_LastWillTopic_Description {
            get {
                return ResourceManager.GetString("MqttDriver_LastWillTopic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT version.
        /// </summary>
        public static string MqttDriver_MqttVersion {
            get {
                return ResourceManager.GetString("MqttDriver_MqttVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the MQTT version number. Default is 3.1.0 if unknown..
        /// </summary>
        public static string MqttDriver_MqttVersion_Description {
            get {
                return ResourceManager.GetString("MqttDriver_MqttVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client password.
        /// </summary>
        public static string MqttDriver_Password {
            get {
                return ResourceManager.GetString("MqttDriver_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for authenticating with the MQTT broker.
        /// </summary>
        public static string MqttDriver_Password_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default port is 1883 for MQTT unless specified otherwise..
        /// </summary>
        public static string MqttDriver_Port_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set MQTT quality of service level.
        /// </summary>
        public static string MqttDriver_QualityOfService {
            get {
                return ResourceManager.GetString("MqttDriver_QualityOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the QoS level for message delivery.
        /// </summary>
        public static string MqttDriver_QualityOfService_Description {
            get {
                return ResourceManager.GetString("MqttDriver_QualityOfService_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes reconnect.
        /// </summary>
        public static string MqttDriver_Reconnect_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Reconnect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string MqttDriver_Reconnect_Name {
            get {
                return ResourceManager.GetString("MqttDriver_Reconnect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay between reconnection attempts.
        /// </summary>
        public static string MqttDriver_ReconnectDelayMs {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectDelayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a delay in milliseconds before trying to reconnect after an error..
        /// </summary>
        public static string MqttDriver_ReconnectDelayMs_Description {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectDelayMs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect using a clean session.
        /// </summary>
        public static string MqttDriver_ReconnectWithoutCleanSession {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectWithoutCleanSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure if the connection should be reestablished with a clean session..
        /// </summary>
        public static string MqttDriver_ReconnectWithoutCleanSession_Description {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectWithoutCleanSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decides if the entire message content should be saved for debugging.
        /// </summary>
        public static string MqttDriver_TraceMessageContent_Description {
            get {
                return ResourceManager.GetString("MqttDriver_TraceMessageContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace message content.
        /// </summary>
        public static string MqttDriver_TraceMessageContent_Name {
            get {
                return ResourceManager.GetString("MqttDriver_TraceMessageContent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client username.
        /// </summary>
        public static string MqttDriver_Username {
            get {
                return ResourceManager.GetString("MqttDriver_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for authenticating with the MQTT broker.
        /// </summary>
        public static string MqttDriver_Username_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS.
        /// </summary>
        public static string MqttDriver_UseTls {
            get {
                return ResourceManager.GetString("MqttDriver_UseTls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to enable a TLS secured connection.
        /// </summary>
        public static string MqttDriver_UseTls_Description {
            get {
                return ResourceManager.GetString("MqttDriver_UseTls_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Topic Identifier.
        /// </summary>
        public static string MqttTopic_Identifier {
            get {
                return ResourceManager.GetString("MqttTopic_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier for MQTT topic, avoiding spaces and following MQTT best practices.
        /// </summary>
        public static string MqttTopic_Identifier_Description {
            get {
                return ResourceManager.GetString("MqttTopic_Identifier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic for responses.
        /// </summary>
        public static string MqttTopic_ResponseTopic {
            get {
                return ResourceManager.GetString("MqttTopic_ResponseTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic to which other clients can respond.
        /// </summary>
        public static string MqttTopic_ResponseTopic_Description {
            get {
                return ResourceManager.GetString("MqttTopic_ResponseTopic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain.
        /// </summary>
        public static string MqttTopic_Retain {
            get {
                return ResourceManager.GetString("MqttTopic_Retain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Messages should be marked as retain.
        /// </summary>
        public static string MqttTopic_Retain_Description {
            get {
                return ResourceManager.GetString("MqttTopic_Retain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic type.
        /// </summary>
        public static string MqttTopic_TopicType {
            get {
                return ResourceManager.GetString("MqttTopic_TopicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message flow direction.
        /// </summary>
        public static string MqttTopic_TopicType_Description {
            get {
                return ResourceManager.GetString("MqttTopic_TopicType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace decoded.
        /// </summary>
        public static string MqttTopic_TraceDecodedMessage {
            get {
                return ResourceManager.GetString("MqttTopic_TraceDecodedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if the decoded message is stored as part of the activity span for debugging purposes.
        /// </summary>
        public static string MqttTopic_TraceDecodedMessage_Description {
            get {
                return ResourceManager.GetString("MqttTopic_TraceDecodedMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT topic for messages implementing IByteSerializable.
        /// </summary>
        public static string MqttTopicIByteSerializable_Description {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Broker for IByteSerializable messages.
        /// </summary>
        public static string MqttTopicIByteSerializable_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of message to be sent.
        /// </summary>
        public static string MqttTopicIByteSerializable_MessageName {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Topic where messages are in JSON format.
        /// </summary>
        public static string MqttTopicJson_Description {
            get {
                return ResourceManager.GetString("MqttTopicJson_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Topic for JSON messages.
        /// </summary>
        public static string MqttTopicJson_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicJson_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums as string.
        /// </summary>
        public static string MqttTopicJson_EnumsAsStrings {
            get {
                return ResourceManager.GetString("MqttTopicJson_EnumsAsStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls enums are encoded as their string names or as numbers.
        /// </summary>
        public static string MqttTopicJson_EnumsAsStrings_Description {
            get {
                return ResourceManager.GetString("MqttTopicJson_EnumsAsStrings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message format.
        /// </summary>
        public static string MqttTopicJson_Format {
            get {
                return ResourceManager.GetString("MqttTopicJson_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializer.
        /// </summary>
        public static string MqttTopicJson_Serializer {
            get {
                return ResourceManager.GetString("MqttTopicJson_Serializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls which serializer library to use.
        /// </summary>
        public static string MqttTopicJson_Serializer_Description {
            get {
                return ResourceManager.GetString("MqttTopicJson_Serializer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Topic where primitive data types are published.
        /// </summary>
        public static string MqttTopicPrimitive_Description {
            get {
                return ResourceManager.GetString("MqttTopicPrimitive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Topic for primitive types.
        /// </summary>
        public static string MqttTopicPrimitive_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicPrimitive_DisplayName", resourceCulture);
            }
        }
    }
}
