//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Drivers.Mqtt.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Moryx.Drivers.Mqtt.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MqttDriver_BrokerUrl_Description {
            get {
                return ResourceManager.GetString("MqttDriver_BrokerUrl_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_BrokerUrl {
            get {
                return ResourceManager.GetString("MqttDriver_BrokerUrl", resourceCulture);
            }
        }
        
        public static string MqttDriver_MqttVersion {
            get {
                return ResourceManager.GetString("MqttDriver_MqttVersion", resourceCulture);
            }
        }
        
        public static string MqttDriver_MqttVersion_Description {
            get {
                return ResourceManager.GetString("MqttDriver_MqttVersion_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_Password {
            get {
                return ResourceManager.GetString("MqttDriver_Password", resourceCulture);
            }
        }
        
        public static string MqttDriver_Password_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Password_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_Port_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Port_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_ReconnectWithoutCleanSession {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectWithoutCleanSession", resourceCulture);
            }
        }
        
        public static string MqttDriver_ReconnectWithoutCleanSession_Description {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectWithoutCleanSession_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_ReconnectDelayMs_Description {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectDelayMs_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_ReconnectDelayMs {
            get {
                return ResourceManager.GetString("MqttDriver_ReconnectDelayMs", resourceCulture);
            }
        }
        
        public static string MqttDriver_Identifier {
            get {
                return ResourceManager.GetString("MqttDriver_Identifier", resourceCulture);
            }
        }
        
        public static string MqttDriver_Username {
            get {
                return ResourceManager.GetString("MqttDriver_Username", resourceCulture);
            }
        }
        
        public static string MqttDriver_Username_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Username_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_UseTls_Description {
            get {
                return ResourceManager.GetString("MqttDriver_UseTls_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_UseTls {
            get {
                return ResourceManager.GetString("MqttDriver_UseTls", resourceCulture);
            }
        }
        
        public static string MqttDriver_QualityOfService_Description {
            get {
                return ResourceManager.GetString("MqttDriver_QualityOfService_Description", resourceCulture);
            }
        }
        
        public static string MqttDriver_QualityOfService {
            get {
                return ResourceManager.GetString("MqttDriver_QualityOfService", resourceCulture);
            }
        }
        
        public static string MqttDriver_DriverState {
            get {
                return ResourceManager.GetString("MqttDriver_DriverState", resourceCulture);
            }
        }
        
        public static string MqttDriver_DisplayName {
            get {
                return ResourceManager.GetString("MqttDriver_DisplayName", resourceCulture);
            }
        }
        
        public static string MqttDriver_Description {
            get {
                return ResourceManager.GetString("MqttDriver_Description", resourceCulture);
            }
        }
        
        public static string MqttTopicIByteSerializable_Description {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_Description", resourceCulture);
            }
        }
        
        public static string MqttTopicIByteSerializable_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_DisplayName", resourceCulture);
            }
        }
        
        public static string MqttTopicIByteSerializable_MessageName {
            get {
                return ResourceManager.GetString("MqttTopicIByteSerializable_MessageName", resourceCulture);
            }
        }
        
        public static string MqttTopic_Identifier_Description {
            get {
                return ResourceManager.GetString("MqttTopic_Identifier_Description", resourceCulture);
            }
        }
        
        public static string MqttTopic_Identifier {
            get {
                return ResourceManager.GetString("MqttTopic_Identifier", resourceCulture);
            }
        }
        
        public static string MqttTopic_ResponseTopic {
            get {
                return ResourceManager.GetString("MqttTopic_ResponseTopic", resourceCulture);
            }
        }
        
        public static string MqttTopic_ResponseTopic_Description {
            get {
                return ResourceManager.GetString("MqttTopic_ResponseTopic_Description", resourceCulture);
            }
        }
        
        public static string MqttTopicPrimitive_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicPrimitive_DisplayName", resourceCulture);
            }
        }
        
        public static string MqttTopicPrimitive_Description {
            get {
                return ResourceManager.GetString("MqttTopicPrimitive_Description", resourceCulture);
            }
        }
        
        public static string MqttTopicJson_DisplayName {
            get {
                return ResourceManager.GetString("MqttTopicJson_DisplayName", resourceCulture);
            }
        }
        
        public static string MqttTopicJson_Description {
            get {
                return ResourceManager.GetString("MqttTopicJson_Description", resourceCulture);
            }
        }
        
        public static string MqttTopicJson_Format {
            get {
                return ResourceManager.GetString("MqttTopicJson_Format", resourceCulture);
            }
        }

        public static string RETAIN
        {
            get
            {
                return ResourceManager.GetString("RETAIN", resourceCulture);
            }
        }
        
        public static string RETAIN_DESCRIPTION
        {
            get
            {
                return ResourceManager.GetString("RETAIN_DESCRIPTION", resourceCulture);
            }
        }
    }
}
