/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderReferenceModel } from '../../models/order-reference-model';

export interface GetOrderReferences$Params {
}

export function getOrderReferences(http: HttpClient, rootUrl: string, params?: GetOrderReferences$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderReferenceModel>>> {
  const rb = new RequestBuilder(rootUrl, getOrderReferences.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderReferenceModel>>;
    })
  );
}

getOrderReferences.PATH = '/api/moryx/materials/integrations/orders';
