/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CellState } from '../models/cell-state';
export interface CellStateChangedModel {
  id?: number;
  state?: CellState;
}
