/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkplanModel } from '../../models/workplan-model';

export interface GetVersions$Params {
  id: number;
}

export function getVersions(http: HttpClient, rootUrl: string, params: GetVersions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkplanModel>>> {
  const rb = new RequestBuilder(rootUrl, getVersions.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkplanModel>>;
    })
  );
}

getVersions.PATH = '/api/moryx/workplans/{id}/versions';
