/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProcessActivityModel } from '../../models/process-activity-model';

export interface ActivitiesUpdatesStream$Params {
}

export function activitiesUpdatesStream(http: HttpClient, rootUrl: string, params?: ActivitiesUpdatesStream$Params, context?: HttpContext): Observable<StrictHttpResponse<ProcessActivityModel>> {
  const rb = new RequestBuilder(rootUrl, activitiesUpdatesStream.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProcessActivityModel>;
    })
  );
}

activitiesUpdatesStream.PATH = '/api/moryx/processes/stream/activities';

