/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServerModuleState } from '../../models/server-module-state';

export interface HealthState$Json$Params {
  moduleName: string;
}

export function healthState$Json(http: HttpClient, rootUrl: string, params: HealthState$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ServerModuleState>> {
  const rb = new RequestBuilder(rootUrl, healthState$Json.PATH, 'get');
  if (params) {
    rb.path('moduleName', params.moduleName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServerModuleState>;
    })
  );
}

healthState$Json.PATH = '/modules/{moduleName}/healthstate';
