/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NodeConnector } from '../models/node-connector';
export interface NodeConnectionPoint {
  connections?: Array<NodeConnector> | null;
  index?: number;
  name?: string | null;
}

