/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
import { MethodEntry } from '@moryx/ngx-web-framework/entry-editor';

/* Code generated by ng-openapi-gen DO NOT EDIT. */


import { WorkplanNodeClassification } from '../models/workplan-node-classification';
export interface WorkplanStepRecipe {
  classification?: WorkplanNodeClassification;
  constructor?: MethodEntry;
  description?: string | null;
  name?: string | null;
  positionLeft?: number;
  positionTop?: number;
  subworkplanId?: number;
  type?: string | null;
}
