<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>Module implementation of Material Management</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moryx.AbstractionLayer\Moryx.AbstractionLayer.csproj" />
    <ProjectReference Include="..\Moryx.Material\Moryx.Material.csproj" />
    <ProjectReference Include="..\Moryx.Runtime\Moryx.Runtime.csproj" />
  </ItemGroup>

</Project>

