/* tslint:disable */
/* eslint-disable */
import { OperationClassification as MoryxOrdersOperationClassification } from '../../../../models/Moryx/Orders/operation-classification';
import { Entry as MoryxSerializationEntry } from '../../../../models/Moryx/Serialization/entry';
export interface OperationModel {
  canAdvice?: boolean;
  canAssign?: boolean;
  canBegin?: boolean;
  canInterrupt?: boolean;
  canReport?: boolean;
  classification?: MoryxOrdersOperationClassification;
  end?: string | null;
  hasDocuments?: boolean;
  hasPartList?: boolean;
  identifier?: string;
  isAborted?: boolean;
  isAmountReached?: boolean;
  isAssigning?: boolean;
  isCreated?: boolean;
  isFailed?: boolean;
  jobIds?: Array<number> | null;
  name?: string | null;
  number?: string | null;
  operationSource?: MoryxSerializationEntry;
  order?: string | null;
  overDeliveryAmount?: number;
  pendingCount?: number;
  plannedEnd?: string;
  plannedStart?: string;
  productId?: number;
  productIdentifier?: string | null;
  productName?: string | null;
  productRevision?: number;
  progressPending?: number;
  progressRunning?: number;
  progressScrap?: number;
  progressSuccess?: number;
  recipeIds?: Array<number> | null;
  recipeName?: string | null;
  reportedFailureCount?: number;
  reportedSuccessCount?: number;
  runningCount?: number;
  scrapCount?: number;
  sortOrder?: number;
  start?: string | null;
  stateDisplayName?: string | null;
  successCount?: number;
  targetCycleTime?: number;
  totalAmount?: number;
  underDeliveryAmount?: number;
  unit?: string | null;
}
