/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationModel } from '../../models/operation-model';

export interface GetOperations$Params {
  orderNumber?: string;
  operationNumber?: string;
}

export function getOperations(http: HttpClient, rootUrl: string, params?: GetOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperationModel>>> {
  const rb = new RequestBuilder(rootUrl, getOperations.PATH, 'get');
  if (params) {
    rb.query('orderNumber', params.orderNumber, {});
    rb.query('operationNumber', params.operationNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OperationModel>>;
    })
  );
}

getOperations.PATH = '/api/moryx/orders';
