// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

using Moryx.AbstractionLayer.Identity;

namespace Moryx.Material;

/// <summary>
/// Announcement that material is inbound to the system.
/// </summary>
/// <param name="RequestReference">Optional cross-reference to an existing <see cref="MaterialRequest"/>.</param>
/// <param name="Material">Material reference. May be omitted if a request is referenced.</param>
/// <param name="AnnouncedQuantity">Announced quantity of inbound material.</param>
/// <param name="Unit">Optional unit of <paramref name="AnnouncedQuantity"/>.</param>
/// <param name="ContainerIdentity">Optional identity of a specific announced container.</param>
/// <param name="ExpectedArrival">Optional expected arrival date and time.</param>
public record MaterialAnnouncement(string? RequestReference, string? Material, double AnnouncedQuantity,
    string? Unit, IIdentity? ContainerIdentity, DateTimeOffset? ExpectedArrival)
{
    /// <summary>
    /// Unique identifier of the announcement. Generated by default.
    /// </summary>
    public string? Id { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// UTC timestamp when the announcement was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}
