// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

using System.ComponentModel.DataAnnotations;
using Moryx.AbstractionLayer.Identity;
using Moryx.Serialization;

namespace Moryx.Material;

/// <summary>
/// Request to provision a quantity of material to the system.
/// </summary>
[Display(Name = "Material Request", Description = "Request to provision a quantity of material to the system.")]
public class MaterialRequest
{
    /// <summary>
    /// Optional unique identifier of the request. May be generated by material management if omitted.
    /// </summary>
    [Display(Name = "Request ID", Description = "Optional unique identifier of the request. May be generated by material management if omitted.")]
    public string? Id { get; set; }

    /// <summary>
    /// Material reference (e.g., product number).
    /// </summary>
    [Display(Name = "Material", Description = "Material reference (e.g., product number).")]
    public string Material { get; set; } = string.Empty;

    /// <summary>
    /// Requested quantity.
    /// </summary>
    [Display(Name = "Requested Quantity", Description = "Quantity of material being requested.")]
    public double RequestedQuantity { get; set; }

    /// <summary>
    /// Optional unit of <see cref="RequestedQuantity"/>.
    /// </summary>
    [Display(Name = "Unit", Description = "Unit of measure for the requested quantity (optional).")]
    public string? Unit { get; set; }

    /// <summary>
    /// Optional identity of a specific container being requested.
    /// </summary>
    [Display(Name = "Container Identity", Description = "Identity of a specific container requested (optional).")]
    [PossibleTypes(typeof(IIdentity))]
    public IIdentity? ContainerIdentity { get; set; }

    /// <summary>
    /// Optional expected arrival.
    /// </summary>
    [Display(Name = "Expected Arrival", Description = "Date and time when the material is expected to arrive (optional).")]
    public DateTimeOffset? ExpectedArrival { get; set; }

    /// <summary>
    /// UTC timestamp when the request was created.
    /// </summary>
    [Display(Name = "Created At", Description = "UTC timestamp when the request was created.")]
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
}
