<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Description>Bundle assembly for Material Management and extensions</Description>
    <PackageTags>MORYX;Manufacturing;Industrial</PackageTags>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moryx.AbstractionLayer\Moryx.AbstractionLayer.csproj" />
    <ProjectReference Include="..\Moryx.Factory\Moryx.Factory.csproj" />
  </ItemGroup>

</Project>

