// <auto-generated />
namespace Marvin.Products.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OutputDescription_OutputType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OutputDescription_OutputType));
        
        string IMigrationMetadata.Id
        {
            get { return "201903011328548_OutputDescription_OutputType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
