/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entry } from '@moryx/ngx-web-framework/entry-editor';
import { PartConnector } from '../models/part-connector';
import { ProductState } from '../models/product-state';
import { RecipeModel } from '../models/recipe-model';
export interface ProductModel {
  id?: number;
  identifier?: string | null;
  name?: string | null;
  parts?: Array<PartConnector> | null;
  properties?: Entry;
  recipes?: Array<RecipeModel> | null;
  revision?: number;
  state?: ProductState;
  type?: string | null;
}

