// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

namespace Moryx.AbstractionLayer.Products;

/// <summary>
/// Current state of a product
/// </summary>
[Flags]
public enum ProductState : int
{
    /// <summary>
    /// Object was created, but not reviewed or released for production
    /// </summary>
    Created = 1 << 0,

    /// <summary>
    /// Product is released and may be manufactured
    /// </summary>
    Released = 1 << 1,

    /// <summary>
    /// Product refers to an old version, that must no longer be manufactured
    /// </summary>
    Deprecated = 1 << 2,

    /// <summary>
    /// Product is generated by the system for internal workflow.
    /// </summary>
    Generated = 1 << 16
}