/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FactoryModel } from '../../models/factory-model';

export interface GetNavigation$Params {
  factoryId: number;
}

export function getNavigation(http: HttpClient, rootUrl: string, params: GetNavigation$Params, context?: HttpContext): Observable<StrictHttpResponse<FactoryModel>> {
  const rb = new RequestBuilder(rootUrl, getNavigation.PATH, 'get');
  if (params) {
    rb.path('factoryId', params.factoryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FactoryModel>;
    })
  );
}

getNavigation.PATH = '/api/moryx/factory-monitor/navigation/{factoryId}';

