-- Script was generated by Devart Entity Developer, Version 5.7.530.0
-- Script date 08.03.2016 12:41:22
-- Target Server: PostgreSQL
-- Server Version: 9.4

-- 
-- Altering a table public."TopParent" 
-- 
ALTER TABLE public."TestTable" ADD COLUMN "NewColumn" INT;

