/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { abortOperation } from '../fn/order-management/abort-operation';
import { AbortOperation$Params } from '../fn/order-management/abort-operation';
import { addOperation } from '../fn/order-management/add-operation';
import { AddOperation$Params } from '../fn/order-management/add-operation';
import { AdviceContext } from '../models/advice-context';
import { adviceOperation } from '../fn/order-management/advice-operation';
import { AdviceOperation$Params } from '../fn/order-management/advice-operation';
import { BeginContext } from '../models/begin-context';
import { beginOperation } from '../fn/order-management/begin-operation';
import { BeginOperation$Params } from '../fn/order-management/begin-operation';
import { DocumentModel } from '../models/document-model';
import { getAdviceContext } from '../fn/order-management/get-advice-context';
import { GetAdviceContext$Params } from '../fn/order-management/get-advice-context';
import { getAssignableRecipes } from '../fn/order-management/get-assignable-recipes';
import { GetAssignableRecipes$Params } from '../fn/order-management/get-assignable-recipes';
import { getBeginContext } from '../fn/order-management/get-begin-context';
import { GetBeginContext$Params } from '../fn/order-management/get-begin-context';
import { getDocuments } from '../fn/order-management/get-documents';
import { GetDocuments$Params } from '../fn/order-management/get-documents';
import { getDocumentStream } from '../fn/order-management/get-document-stream';
import { GetDocumentStream$Params } from '../fn/order-management/get-document-stream';
import { getInterruptContext } from '../fn/order-management/get-interrupt-context';
import { GetInterruptContext$Params } from '../fn/order-management/get-interrupt-context';
import { getLogs } from '../fn/order-management/get-logs';
import { GetLogs$Params } from '../fn/order-management/get-logs';
import { getOperation } from '../fn/order-management/get-operation';
import { GetOperation$Params } from '../fn/order-management/get-operation';
import { getOperations } from '../fn/order-management/get-operations';
import { GetOperations$Params } from '../fn/order-management/get-operations';
import { getProductParts } from '../fn/order-management/get-product-parts';
import { GetProductParts$Params } from '../fn/order-management/get-product-parts';
import { getReportContext } from '../fn/order-management/get-report-context';
import { GetReportContext$Params } from '../fn/order-management/get-report-context';
import { interruptOperation } from '../fn/order-management/interrupt-operation';
import { InterruptOperation$Params } from '../fn/order-management/interrupt-operation';
import { OperationChangedModel } from '../models/operation-changed-model';
import { OperationLogMessageModel } from '../models/operation-log-message-model';
import { OperationModel } from '../models/operation-model';
import { OperationRecipeModel } from '../models/operation-recipe-model';
import { operationStream } from '../fn/order-management/operation-stream';
import { OperationStream$Params } from '../fn/order-management/operation-stream';
import { ProductPartModel } from '../models/product-part-model';
import { reload } from '../fn/order-management/reload';
import { Reload$Params } from '../fn/order-management/reload';
import { ReportContext } from '../models/report-context';
import { reportOperation } from '../fn/order-management/report-operation';
import { ReportOperation$Params } from '../fn/order-management/report-operation';
import { updateOperation } from '../fn/order-management/update-operation';
import { UpdateOperation$Params } from '../fn/order-management/update-operation';

@Injectable({ providedIn: 'root' })
export class OrderManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOperations()` */
  static readonly GetOperationsPath = '/api/moryx/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOperations()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperations$Response(params?: GetOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperationModel>>> {
    const obs = getOperations(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOperations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperations(params?: GetOperations$Params, context?: HttpContext): Observable<Array<OperationModel>> {
    const resp = this.getOperations$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<OperationModel>>): Array<OperationModel> => r.body)
    );
  }

  /** Path part for operation `addOperation()` */
  static readonly AddOperationPath = '/api/moryx/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addOperation()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  addOperation$Response(params?: AddOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationModel>> {
    const obs = addOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addOperation$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  addOperation(params?: AddOperation$Params, context?: HttpContext): Observable<OperationModel> {
    const resp = this.addOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OperationModel>): OperationModel => r.body)
    );
  }

  /** Path part for operation `operationStream()` */
  static readonly OperationStreamPath = '/api/moryx/orders/stream';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `operationStream()` instead.
   *
   * This method doesn't expect any request body.
   */
  operationStream$Response(params?: OperationStream$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationChangedModel>> {
    const obs = operationStream(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `operationStream$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  operationStream(params?: OperationStream$Params, context?: HttpContext): Observable<OperationChangedModel> {
    const resp = this.operationStream$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OperationChangedModel>): OperationChangedModel => r.body)
    );
  }

  /** Path part for operation `getOperation()` */
  static readonly GetOperationPath = '/api/moryx/orders/{guid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOperation()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperation$Response(params: GetOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationModel>> {
    const obs = getOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOperation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperation(params: GetOperation$Params, context?: HttpContext): Observable<OperationModel> {
    const resp = this.getOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<OperationModel>): OperationModel => r.body)
    );
  }

  /** Path part for operation `getDocuments()` */
  static readonly GetDocumentsPath = '/api/moryx/orders/{guid}/documents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocuments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocuments$Response(params: GetDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DocumentModel>>> {
    const obs = getDocuments(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocuments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocuments(params: GetDocuments$Params, context?: HttpContext): Observable<Array<DocumentModel>> {
    const resp = this.getDocuments$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<DocumentModel>>): Array<DocumentModel> => r.body)
    );
  }

  /** Path part for operation `getDocumentStream()` */
  static readonly GetDocumentStreamPath = '/api/moryx/orders/{guid}/document/{identifier}/stream';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDocumentStream()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentStream$Response(params: GetDocumentStream$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    const obs = getDocumentStream(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDocumentStream$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDocumentStream(params: GetDocumentStream$Params, context?: HttpContext): Observable<Blob> {
    const resp = this.getDocumentStream$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `getProductParts()` */
  static readonly GetProductPartsPath = '/api/moryx/orders/{guid}/productparts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductParts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductParts$Response(params: GetProductParts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductPartModel>>> {
    const obs = getProductParts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductParts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductParts(params: GetProductParts$Params, context?: HttpContext): Observable<Array<ProductPartModel>> {
    const resp = this.getProductParts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ProductPartModel>>): Array<ProductPartModel> => r.body)
    );
  }

  /** Path part for operation `getBeginContext()` */
  static readonly GetBeginContextPath = '/api/moryx/orders/{guid}/begin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBeginContext()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBeginContext$Response(params: GetBeginContext$Params, context?: HttpContext): Observable<StrictHttpResponse<BeginContext>> {
    const obs = getBeginContext(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBeginContext$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBeginContext(params: GetBeginContext$Params, context?: HttpContext): Observable<BeginContext> {
    const resp = this.getBeginContext$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<BeginContext>): BeginContext => r.body)
    );
  }

  /** Path part for operation `beginOperation()` */
  static readonly BeginOperationPath = '/api/moryx/orders/{guid}/begin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `beginOperation()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  beginOperation$Response(params: BeginOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = beginOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `beginOperation$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  beginOperation(params: BeginOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.beginOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getReportContext()` */
  static readonly GetReportContextPath = '/api/moryx/orders/{guid}/report';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getReportContext()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportContext$Response(params: GetReportContext$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportContext>> {
    const obs = getReportContext(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getReportContext$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getReportContext(params: GetReportContext$Params, context?: HttpContext): Observable<ReportContext> {
    const resp = this.getReportContext$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ReportContext>): ReportContext => r.body)
    );
  }

  /** Path part for operation `reportOperation()` */
  static readonly ReportOperationPath = '/api/moryx/orders/{guid}/report';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportOperation()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  reportOperation$Response(params: ReportOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = reportOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportOperation$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  reportOperation(params: ReportOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.reportOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getInterruptContext()` */
  static readonly GetInterruptContextPath = '/api/moryx/orders/{guid}/interrupt';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getInterruptContext()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInterruptContext$Response(params: GetInterruptContext$Params, context?: HttpContext): Observable<StrictHttpResponse<ReportContext>> {
    const obs = getInterruptContext(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getInterruptContext$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getInterruptContext(params: GetInterruptContext$Params, context?: HttpContext): Observable<ReportContext> {
    const resp = this.getInterruptContext$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ReportContext>): ReportContext => r.body)
    );
  }

  /** Path part for operation `interruptOperation()` */
  static readonly InterruptOperationPath = '/api/moryx/orders/{guid}/interrupt';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `interruptOperation()` instead.
   *
   * This method doesn't expect any request body.
   */
  interruptOperation$Response(params: InterruptOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = interruptOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `interruptOperation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  interruptOperation(params: InterruptOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.interruptOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAdviceContext()` */
  static readonly GetAdviceContextPath = '/api/moryx/orders/{guid}/advice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAdviceContext()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdviceContext$Response(params: GetAdviceContext$Params, context?: HttpContext): Observable<StrictHttpResponse<AdviceContext>> {
    const obs = getAdviceContext(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAdviceContext$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdviceContext(params: GetAdviceContext$Params, context?: HttpContext): Observable<AdviceContext> {
    const resp = this.getAdviceContext$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AdviceContext>): AdviceContext => r.body)
    );
  }

  /** Path part for operation `adviceOperation()` */
  static readonly AdviceOperationPath = '/api/moryx/orders/{guid}/advice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adviceOperation()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adviceOperation$Response(params: AdviceOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = adviceOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adviceOperation$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adviceOperation(params: AdviceOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.adviceOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getLogs()` */
  static readonly GetLogsPath = '/api/moryx/orders/{guid}/logs';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLogs()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLogs$Response(params: GetLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperationLogMessageModel>>> {
    const obs = getLogs(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLogs$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLogs(params: GetLogs$Params, context?: HttpContext): Observable<Array<OperationLogMessageModel>> {
    const resp = this.getLogs$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<OperationLogMessageModel>>): Array<OperationLogMessageModel> => r.body)
    );
  }

  /** Path part for operation `getAssignableRecipes()` */
  static readonly GetAssignableRecipesPath = '/api/moryx/orders/recipes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAssignableRecipes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAssignableRecipes$Response(params?: GetAssignableRecipes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperationRecipeModel>>> {
    const obs = getAssignableRecipes(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAssignableRecipes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAssignableRecipes(params?: GetAssignableRecipes$Params, context?: HttpContext): Observable<Array<OperationRecipeModel>> {
    const resp = this.getAssignableRecipes$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<OperationRecipeModel>>): Array<OperationRecipeModel> => r.body)
    );
  }

  /** Path part for operation `abortOperation()` */
  static readonly AbortOperationPath = '/api/moryx/orders/{guid}/abort';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `abortOperation()` instead.
   *
   * This method doesn't expect any request body.
   */
  abortOperation$Response(params: AbortOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = abortOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `abortOperation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  abortOperation(params: AbortOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.abortOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateOperation()` */
  static readonly UpdateOperationPath = '/api/moryx/orders/{guid}/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOperation()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  updateOperation$Response(params: UpdateOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateOperation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOperation$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  updateOperation(params: UpdateOperation$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateOperation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reload()` */
  static readonly ReloadPath = '/api/moryx/orders/{guid}/reload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reload()` instead.
   *
   * This method doesn't expect any request body.
   */
  reload$Response(params: Reload$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = reload(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reload$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reload(params: Reload$Params, context?: HttpContext): Observable<void> {
    const resp = this.reload$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
