//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.AbstractionLayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.AbstractionLayer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity has conflicts with existing products and revisions!.
        /// </summary>
        internal static string IdentityConflictException_IdentityConflictMessage {
            get {
                return ResourceManager.GetString("IdentityConflictException_IdentityConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity can not be used for duplicates of the template!.
        /// </summary>
        internal static string IdentityConflictException_InvalidTemplateMessage {
            get {
                return ResourceManager.GetString("IdentityConflictException_InvalidTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found for id: {0}.
        /// </summary>
        internal static string ProductNotFoundException_Message {
            get {
                return ResourceManager.GetString("ProductNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy was detached and can no longer be used!.
        /// </summary>
        internal static string ProxyDetachedException_Message {
            get {
                return ResourceManager.GetString("ProxyDetachedException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe with id &apos;{0}&apos; not found!.
        /// </summary>
        internal static string RecipeNotFoundException_Message {
            get {
                return ResourceManager.GetString("RecipeNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource found providing capabilities or too many matches: {0}.
        /// </summary>
        internal static string ResourceNotFoundException_ByCapabilities_Message {
            get {
                return ResourceManager.GetString("ResourceNotFoundException_ByCapabilities_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource found with id: {0}.
        /// </summary>
        internal static string ResourceNotFoundException_ById_Message {
            get {
                return ResourceManager.GetString("ResourceNotFoundException_ById_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver does not support segments.
        /// </summary>
        internal static string SegmentsNotSupportedException_Message {
            get {
                return ResourceManager.GetString("SegmentsNotSupportedException_Message", resourceCulture);
            }
        }
    }
}
