<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Moryx\Moryx.csproj" />
    <ProjectReference Include="..\..\Moryx.AbstractionLayer.TestTools\Moryx.AbstractionLayer.TestTools.csproj" />
    <ProjectReference Include="..\..\Moryx.Drivers.Mqtt\Moryx.Drivers.Mqtt.csproj" />
    <ProjectReference Include="..\..\Moryx.TestTools.UnitTest\Moryx.TestTools.UnitTest.csproj" />
  </ItemGroup>

</Project>
