/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { containerChanges } from '../fn/material-management/container-changes';
import { ContainerChanges$Params } from '../fn/material-management/container-changes';
import { getAll } from '../fn/material-management/get-all';
import { GetAll$Params } from '../fn/material-management/get-all';
import { getTypes } from '../fn/material-management/get-types';
import { GetTypes$Params } from '../fn/material-management/get-types';
import { hasOrderIntegration } from '../fn/material-management/has-order-integration';
import { HasOrderIntegration$Params } from '../fn/material-management/has-order-integration';
import { MaterialContainerModel } from '../models/material-container-model';
import { MaterialContainerTypeModel } from '../models/material-container-type-model';
import { OrderReferenceModel } from '../models/order-reference-model';
import { preAdviceAsync } from '../fn/material-management/pre-advice-async';
import { PreAdviceAsync$Params } from '../fn/material-management/pre-advice-async';

@Injectable({ providedIn: 'root' })
export class MaterialManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getContainers()` */
  static readonly GetContainersPath = '/api/moryx/materials/containers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getContainers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContainers$Response(params?: GetContainers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MaterialContainerModel>>> {
    const obs = getContainers(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getContainers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getContainers(params?: GetContainers$Params, context?: HttpContext): Observable<Array<MaterialContainerModel>> {
    const resp = this.getContainers$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<MaterialContainerModel>>): Array<MaterialContainerModel> => r.body)
    );
  }

  /** Path part for operation `getTypes()` */
  static readonly GetTypesPath = '/api/moryx/materials/containers/types';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTypes$Response(params?: GetTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MaterialContainerTypeModel>>> {
    const obs = getTypes(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTypes(params?: GetTypes$Params, context?: HttpContext): Observable<Array<MaterialContainerTypeModel>> {
    const resp = this.getTypes$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<MaterialContainerTypeModel>>): Array<MaterialContainerTypeModel> => r.body)
    );
  }

  /** Path part for operation `preAdviceAsync()` */
  static readonly PreAdviceAsyncPath = '/api/moryx/materials/containers/pre-advice';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preAdviceAsync()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  preAdviceAsync$Response(params?: PreAdviceAsync$Params, context?: HttpContext): Observable<StrictHttpResponse<MaterialContainerModel>> {
    const obs = preAdviceAsync(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preAdviceAsync$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  preAdviceAsync(params?: PreAdviceAsync$Params, context?: HttpContext): Observable<MaterialContainerModel> {
    const resp = this.preAdviceAsync$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<MaterialContainerModel>): MaterialContainerModel => r.body)
    );
  }

  /** Path part for operation `containerChanges()` */
  static readonly ContainerChangesPath = '/api/moryx/materials/containers/stream';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `containerChanges()` instead.
   *
   * This method doesn't expect any request body.
   */
  containerChanges$Response(params?: ContainerChanges$Params, context?: HttpContext): Observable<StrictHttpResponse<MaterialContainerModel>> {
    const obs = containerChanges(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `containerChanges$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  containerChanges(params?: ContainerChanges$Params, context?: HttpContext): Observable<MaterialContainerModel> {
    const resp = this.containerChanges$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<MaterialContainerModel>): MaterialContainerModel => r.body)
    );
  }

  /** Path part for operation `hasOrderIntegration()` */
  static readonly HasOrderIntegrationPath = '/api/moryx/materials/integrations/orders/available';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hasOrderIntegration()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasOrderIntegration$Response(params?: HasOrderIntegration$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    const obs = hasOrderIntegration(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hasOrderIntegration$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasOrderIntegration(params?: HasOrderIntegration$Params, context?: HttpContext): Observable<boolean> {
    const resp = this.hasOrderIntegration$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getOrderReferences()` */
  static readonly GetOrderReferencesPath = '/api/moryx/materials/integrations/orders';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrderReferences()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderReferences$Response(params?: GetOrderReferences$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderReferenceModel>>> {
    const obs = getOrderReferences(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrderReferences$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderReferences(params?: GetOrderReferences$Params, context?: HttpContext): Observable<Array<OrderReferenceModel>> {
    const resp = this.getOrderReferences$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<OrderReferenceModel>>): Array<OrderReferenceModel> => r.body)
    );
  }

}
