/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OperationModel } from '../models/operation-model';
import { ReportModel } from '../models/report-model';
export interface OperationReportedModel {
  operationModel?: OperationModel;
  report?: ReportModel;
}
