/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RestrictionSeverity } from '../models/restriction-severity';
export interface RestrictionDescription {
  severity?: RestrictionSeverity;
  text?: string | null;
}
