// Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
// Licensed under the Apache License, Version 2.0

namespace Moryx.ProcessData.Endpoints.Models
{
    public class MeasurandResponse : Measurand
    {
        public MeasurandResponse(string name) : base(name)
        {
        }

        /// <summary>
        /// Name of the Measurand as generated by the source module. 
        /// This property can be removed, when the PdmAdapters are removed.
        /// </summary>
        public string GeneratedName { get; internal set; }

        /// <summary>
        /// Description of the measurand
        /// </summary>
        public string Description { get; internal set; }

        /// <summary>
        /// Module which is the source of this measurand
        /// </summary>
        public string Source { get; internal set; }
    }
}
