/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResourceModel as MoryxAbstractionLayerResourcesEndpointsResourceModel } from '../../../../../models/Moryx/AbstractionLayer/Resources/Endpoints/resource-model';
export interface ResourceReferenceModel {
  name?: string | null;
  targets?: Array<MoryxAbstractionLayerResourcesEndpointsResourceModel> | null;
}
