/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReferenceFilter as MoryxAbstractionLayerResourcesEndpointsReferenceFilter } from '../../../../../models/Moryx/AbstractionLayer/Resources/Endpoints/reference-filter';
export interface ResourceQuery {
  includedReferences?: Array<MoryxAbstractionLayerResourcesEndpointsReferenceFilter> | null;
  referenceCondition?: MoryxAbstractionLayerResourcesEndpointsReferenceFilter;
  referenceRecursion?: boolean;
  types?: Array<string> | null;
}
