//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.ControlSystem.ProcessEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.ControlSystem.ProcessEngine.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create activity from task {0} of recipe {1} ähnelt.
        /// </summary>
        public static string ActivityProvider_CreationException_Message {
            get {
                return ResourceManager.GetString("ActivityProvider_CreationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity creation failed ähnelt.
        /// </summary>
        public static string ActivityProvider_CreationException_Title {
            get {
                return ResourceManager.GetString("ActivityProvider_CreationException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity timeout of {1} seconds reached for {0}. ähnelt.
        /// </summary>
        public static string ActivityTimeoutObserver_ActivityTimeout_Message {
            get {
                return ResourceManager.GetString("ActivityTimeoutObserver_ActivityTimeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity Timeout ähnelt.
        /// </summary>
        public static string ActivityTimeoutObserver_ActivityTimeout_Title {
            get {
                return ResourceManager.GetString("ActivityTimeoutObserver_ActivityTimeout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aborting ähnelt.
        /// </summary>
        public static string JobStates_Aborting {
            get {
                return ResourceManager.GetString("JobStates_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cleaning Up ähnelt.
        /// </summary>
        public static string JobStates_Cleanup {
            get {
                return ResourceManager.GetString("JobStates_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Completing ähnelt.
        /// </summary>
        public static string JobStates_Completing {
            get {
                return ResourceManager.GetString("JobStates_Completing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started ähnelt.
        /// </summary>
        public static string JobStates_Dispatched {
            get {
                return ResourceManager.GetString("JobStates_Dispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created ähnelt.
        /// </summary>
        public static string JobStates_Initial {
            get {
                return ResourceManager.GetString("JobStates_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interrupted ähnelt.
        /// </summary>
        public static string JobStates_Interrupted {
            get {
                return ResourceManager.GetString("JobStates_Interrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interrupting ähnelt.
        /// </summary>
        public static string JobStates_Interrupting {
            get {
                return ResourceManager.GetString("JobStates_Interrupting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running ähnelt.
        /// </summary>
        public static string JobStates_Running {
            get {
                return ResourceManager.GetString("JobStates_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting ähnelt.
        /// </summary>
        public static string JobStates_Waiting {
            get {
                return ResourceManager.GetString("JobStates_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot find resource for {0}. ähnelt.
        /// </summary>
        public static string ResourceAssignment_UnassignedActivityNotification_Message {
            get {
                return ResourceManager.GetString("ResourceAssignment_UnassignedActivityNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unassigned Activity ähnelt.
        /// </summary>
        public static string ResourceAssignment_UnassignedActivityNotification_Title {
            get {
                return ResourceManager.GetString("ResourceAssignment_UnassignedActivityNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot run setup for &apos;{0}&apos;. Please contact the service. ähnelt.
        /// </summary>
        public static string SetupJobData_RetryFailedNotification_Message {
            get {
                return ResourceManager.GetString("SetupJobData_RetryFailedNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup Error ähnelt.
        /// </summary>
        public static string SetupJobData_RetryFailedNotification_Title {
            get {
                return ResourceManager.GetString("SetupJobData_RetryFailedNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open output on step {0} ähnelt.
        /// </summary>
        public static string WorkplanValidation_OutputUnset {
            get {
                return ResourceManager.GetString("WorkplanValidation_OutputUnset", resourceCulture);
            }
        }
    }
}
