//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Drivers.OpcUa.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Moryx.Drivers.OpcUa.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string OpcUaDriver_StateName {
            get {
                return ResourceManager.GetString("OpcUaDriver_StateName", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_DisplayName {
            get {
                return ResourceManager.GetString("OpcUaDriver_DisplayName", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_ServerStatus {
            get {
                return ResourceManager.GetString("OpcUaDriver_ServerStatus", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_DeviceSet {
            get {
                return ResourceManager.GetString("OpcUaDriver_DeviceSet", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_DeviceSet_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_DeviceSet_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_Nodes {
            get {
                return ResourceManager.GetString("OpcUaDriver_Nodes", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_NodeIdAlias {
            get {
                return ResourceManager.GetString("OpcUaDriver_NodeIdAlias", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_DefaultSubscriptions {
            get {
                return ResourceManager.GetString("OpcUaDriver_DefaultSubscriptions", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_OpcUaServerUrl {
            get {
                return ResourceManager.GetString("OpcUaDriver_OpcUaServerUrl", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_OpcUaServerUrl_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_OpcUaServerUrl_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_Identifier {
            get {
                return ResourceManager.GetString("OpcUaDriver_Identifier", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_OpcUaServerPort {
            get {
                return ResourceManager.GetString("OpcUaDriver_OpcUaServerPort", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_Username {
            get {
                return ResourceManager.GetString("OpcUaDriver_Username", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_Password {
            get {
                return ResourceManager.GetString("OpcUaDriver_Password", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_UseEncryption_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_UseEncryption_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_UseEncryption {
            get {
                return ResourceManager.GetString("OpcUaDriver_UseEncryption", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_FilePathClientConfig {
            get {
                return ResourceManager.GetString("OpcUaDriver_FilePathClientConfig", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_FilePathClientConfig_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_FilePathClientConfig_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_ReconnectionPeriod_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_ReconnectionPeriod_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_ReconnectionPeriod {
            get {
                return ResourceManager.GetString("OpcUaDriver_ReconnectionPeriod", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_PublishingInterval {
            get {
                return ResourceManager.GetString("OpcUaDriver_PublishingInterval", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_PublishingInterval_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_PublishingInterval_Description", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_SamplingInterval {
            get {
                return ResourceManager.GetString("OpcUaDriver_SamplingInterval", resourceCulture);
            }
        }
        
        public static string OpcUaDriver_SamplingInterval_Description {
            get {
                return ResourceManager.GetString("OpcUaDriver_SamplingInterval_Description", resourceCulture);
            }
        }
    }
}
