/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum MaterialStateClassificationModel {
  Uninitialized = 'Uninitialized',
  Requested = 'Requested',
  Inbound = 'Inbound',
  Available = 'Available',
  Outbound = 'Outbound',
  Deregistered = 'Deregistered'
}
