/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AssemblyModel } from '../models/assembly-model';
import { FailureBehaviour } from '../models/failure-behaviour';
import { ModuleNotificationModel } from '../models/module-notification-model';
import { ModuleStartBehaviour } from '../models/module-start-behaviour';
import { ServerModuleState } from '../models/server-module-state';
export interface ServerModuleModel {
  assembly?: AssemblyModel;
  dependencies?: Array<ServerModuleModel> | null;
  failureBehaviour?: FailureBehaviour;
  healthState?: ServerModuleState;
  name?: string | null;
  notifications?: Array<ModuleNotificationModel> | null;
  startBehaviour?: ModuleStartBehaviour;
}
