/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FactoryModel {
  backgroundURL?: string | null;
  id?: number;
  parentId?: number;
  title?: string | null;
}

