/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CellLocationModel } from '../models/cell-location-model';
export interface VisualizableItemModel {
  iconName?: string | null;
  id?: number;
  isACell?: boolean;
  location?: CellLocationModel;
}

