/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
import { Entry } from '@moryx/ngx-web-framework/entry-editor';

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MethodEntry {
  description?: string | null;
  displayName?: string | null;
  isAsync?: boolean;
  isConstructor?: boolean;
  name?: string | null;
  parameters?: Entry;
}
