/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { allCells } from '../fn/factory-monitor/all-cells';
import { AllCells$Params } from '../fn/factory-monitor/all-cells';
import { allCells$Plain } from '../fn/factory-monitor/all-cells-plain';
import { AllCells$Plain$Params } from '../fn/factory-monitor/all-cells-plain';
import { CellLocationModel } from '../models/cell-location-model';
import { CellPropertySettings } from '../models/cell-property-settings';
import { cellSettings } from '../fn/factory-monitor/cell-settings';
import { CellSettings$Params } from '../fn/factory-monitor/cell-settings';
import { changeBackground } from '../fn/factory-monitor/change-background';
import { ChangeBackground$Params } from '../fn/factory-monitor/change-background';
import { factoryContent } from '../fn/factory-monitor/factory-content';
import { FactoryContent$Params } from '../fn/factory-monitor/factory-content';
import { factoryContent$Plain } from '../fn/factory-monitor/factory-content-plain';
import { FactoryContent$Plain$Params } from '../fn/factory-monitor/factory-content-plain';
import { FactoryModel } from '../models/factory-model';
import { FactoryStateModel } from '../models/factory-state-model';
import { factoryStatesStream } from '../fn/factory-monitor/factory-states-stream';
import { FactoryStatesStream$Params } from '../fn/factory-monitor/factory-states-stream';
import { factoryStatesStream$Plain } from '../fn/factory-monitor/factory-states-stream-plain';
import { FactoryStatesStream$Plain$Params } from '../fn/factory-monitor/factory-states-stream-plain';
import { getCellPropertiesSettings } from '../fn/factory-monitor/get-cell-properties-settings';
import { GetCellPropertiesSettings$Params } from '../fn/factory-monitor/get-cell-properties-settings';
import { getCellPropertiesSettings$Plain } from '../fn/factory-monitor/get-cell-properties-settings-plain';
import { GetCellPropertiesSettings$Plain$Params } from '../fn/factory-monitor/get-cell-properties-settings-plain';
import { getNavigation } from '../fn/factory-monitor/get-navigation';
import { GetNavigation$Params } from '../fn/factory-monitor/get-navigation';
import { getNavigation$Plain } from '../fn/factory-monitor/get-navigation-plain';
import { GetNavigation$Plain$Params } from '../fn/factory-monitor/get-navigation-plain';
import { getRoutes } from '../fn/factory-monitor/get-routes';
import { GetRoutes$Params } from '../fn/factory-monitor/get-routes';
import { getRoutes$Plain } from '../fn/factory-monitor/get-routes-plain';
import { GetRoutes$Plain$Params } from '../fn/factory-monitor/get-routes-plain';
import { initialFactoryState } from '../fn/factory-monitor/initial-factory-state';
import { InitialFactoryState$Params } from '../fn/factory-monitor/initial-factory-state';
import { initialFactoryState$Plain } from '../fn/factory-monitor/initial-factory-state-plain';
import { InitialFactoryState$Plain$Params } from '../fn/factory-monitor/initial-factory-state-plain';
import { moveCell } from '../fn/factory-monitor/move-cell';
import { MoveCell$Params } from '../fn/factory-monitor/move-cell';
import { moveCell$Plain } from '../fn/factory-monitor/move-cell-plain';
import { MoveCell$Plain$Params } from '../fn/factory-monitor/move-cell-plain';
import { OrderChangedModel } from '../models/order-changed-model';
import { traceRoute } from '../fn/factory-monitor/trace-route';
import { TraceRoute$Params } from '../fn/factory-monitor/trace-route';
import { TransportRouteModel } from '../models/transport-route-model';
import { VisualizableItemModel } from '../models/visualizable-item-model';

@Injectable({ providedIn: 'root' })
export class FactoryMonitorService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `initialFactoryState()` */
  static readonly InitialFactoryStatePath = '/api/moryx/factory-monitor/state';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initialFactoryState$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  initialFactoryState$Plain$Response(params?: InitialFactoryState$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<FactoryStateModel>> {
    return initialFactoryState$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initialFactoryState$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initialFactoryState$Plain(params?: InitialFactoryState$Plain$Params, context?: HttpContext): Observable<FactoryStateModel> {
    return this.initialFactoryState$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactoryStateModel>): FactoryStateModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `initialFactoryState()` instead.
   *
   * This method doesn't expect any request body.
   */
  initialFactoryState$Response(params?: InitialFactoryState$Params, context?: HttpContext): Observable<StrictHttpResponse<FactoryStateModel>> {
    return initialFactoryState(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `initialFactoryState$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  initialFactoryState(params?: InitialFactoryState$Params, context?: HttpContext): Observable<FactoryStateModel> {
    return this.initialFactoryState$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactoryStateModel>): FactoryStateModel => r.body)
    );
  }

  /** Path part for operation `allCells()` */
  static readonly AllCellsPath = '/api/moryx/factory-monitor/cells';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `allCells$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  allCells$Plain$Response(params?: AllCells$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VisualizableItemModel>>> {
    return allCells$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `allCells$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  allCells$Plain(params?: AllCells$Plain$Params, context?: HttpContext): Observable<Array<VisualizableItemModel>> {
    return this.allCells$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VisualizableItemModel>>): Array<VisualizableItemModel> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `allCells()` instead.
   *
   * This method doesn't expect any request body.
   */
  allCells$Response(params?: AllCells$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VisualizableItemModel>>> {
    return allCells(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `allCells$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  allCells(params?: AllCells$Params, context?: HttpContext): Observable<Array<VisualizableItemModel>> {
    return this.allCells$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VisualizableItemModel>>): Array<VisualizableItemModel> => r.body)
    );
  }

  /** Path part for operation `factoryContent()` */
  static readonly FactoryContentPath = '/api/moryx/factory-monitor/factory-content/{factoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `factoryContent$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryContent$Plain$Response(params: FactoryContent$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VisualizableItemModel>>> {
    return factoryContent$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `factoryContent$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryContent$Plain(params: FactoryContent$Plain$Params, context?: HttpContext): Observable<Array<VisualizableItemModel>> {
    return this.factoryContent$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VisualizableItemModel>>): Array<VisualizableItemModel> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `factoryContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryContent$Response(params: FactoryContent$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<VisualizableItemModel>>> {
    return factoryContent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `factoryContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryContent(params: FactoryContent$Params, context?: HttpContext): Observable<Array<VisualizableItemModel>> {
    return this.factoryContent$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<VisualizableItemModel>>): Array<VisualizableItemModel> => r.body)
    );
  }

  /** Path part for operation `getNavigation()` */
  static readonly GetNavigationPath = '/api/moryx/factory-monitor/navigation/{factoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getNavigation$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNavigation$Plain$Response(params: GetNavigation$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<FactoryModel>> {
    return getNavigation$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getNavigation$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNavigation$Plain(params: GetNavigation$Plain$Params, context?: HttpContext): Observable<FactoryModel> {
    return this.getNavigation$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactoryModel>): FactoryModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getNavigation()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNavigation$Response(params: GetNavigation$Params, context?: HttpContext): Observable<StrictHttpResponse<FactoryModel>> {
    return getNavigation(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getNavigation$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getNavigation(params: GetNavigation$Params, context?: HttpContext): Observable<FactoryModel> {
    return this.getNavigation$Response(params, context).pipe(
      map((r: StrictHttpResponse<FactoryModel>): FactoryModel => r.body)
    );
  }

  /** Path part for operation `factoryStatesStream()` */
  static readonly FactoryStatesStreamPath = '/api/moryx/factory-monitor/state-stream';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `factoryStatesStream$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryStatesStream$Plain$Response(params?: FactoryStatesStream$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderChangedModel>> {
    return factoryStatesStream$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `factoryStatesStream$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryStatesStream$Plain(params?: FactoryStatesStream$Plain$Params, context?: HttpContext): Observable<OrderChangedModel> {
    return this.factoryStatesStream$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderChangedModel>): OrderChangedModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `factoryStatesStream()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryStatesStream$Response(params?: FactoryStatesStream$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderChangedModel>> {
    return factoryStatesStream(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `factoryStatesStream$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  factoryStatesStream(params?: FactoryStatesStream$Params, context?: HttpContext): Observable<OrderChangedModel> {
    return this.factoryStatesStream$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderChangedModel>): OrderChangedModel => r.body)
    );
  }

  /** Path part for operation `moveCell()` */
  static readonly MoveCellPath = '/api/moryx/factory-monitor/move-cell';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `moveCell$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  moveCell$Plain$Response(params?: MoveCell$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CellLocationModel>> {
    return moveCell$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `moveCell$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  moveCell$Plain(params?: MoveCell$Plain$Params, context?: HttpContext): Observable<CellLocationModel> {
    return this.moveCell$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CellLocationModel>): CellLocationModel => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `moveCell()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  moveCell$Response(params?: MoveCell$Params, context?: HttpContext): Observable<StrictHttpResponse<CellLocationModel>> {
    return moveCell(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `moveCell$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  moveCell(params?: MoveCell$Params, context?: HttpContext): Observable<CellLocationModel> {
    return this.moveCell$Response(params, context).pipe(
      map((r: StrictHttpResponse<CellLocationModel>): CellLocationModel => r.body)
    );
  }

  /** Path part for operation `changeBackground()` */
  static readonly ChangeBackgroundPath = '/api/moryx/factory-monitor/background';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeBackground()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeBackground$Response(params?: ChangeBackground$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return changeBackground(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeBackground$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeBackground(params?: ChangeBackground$Params, context?: HttpContext): Observable<void> {
    return this.changeBackground$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getCellPropertiesSettings()` */
  static readonly GetCellPropertiesSettingsPath = '/api/moryx/factory-monitor/cell-properties/{identifier}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCellPropertiesSettings$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCellPropertiesSettings$Plain$Response(params: GetCellPropertiesSettings$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: CellPropertySettings;
}>> {
    return getCellPropertiesSettings$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCellPropertiesSettings$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCellPropertiesSettings$Plain(params: GetCellPropertiesSettings$Plain$Params, context?: HttpContext): Observable<{
[key: string]: CellPropertySettings;
}> {
    return this.getCellPropertiesSettings$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: CellPropertySettings;
}>): {
[key: string]: CellPropertySettings;
} => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCellPropertiesSettings()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCellPropertiesSettings$Response(params: GetCellPropertiesSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: CellPropertySettings;
}>> {
    return getCellPropertiesSettings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCellPropertiesSettings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCellPropertiesSettings(params: GetCellPropertiesSettings$Params, context?: HttpContext): Observable<{
[key: string]: CellPropertySettings;
}> {
    return this.getCellPropertiesSettings$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: CellPropertySettings;
}>): {
[key: string]: CellPropertySettings;
} => r.body)
    );
  }

  /** Path part for operation `traceRoute()` */
  static readonly TraceRoutePath = '/api/moryx/factory-monitor/traceroute';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `traceRoute()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  traceRoute$Response(params?: TraceRoute$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return traceRoute(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `traceRoute$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  traceRoute(params?: TraceRoute$Params, context?: HttpContext): Observable<void> {
    return this.traceRoute$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `cellSettings()` */
  static readonly CellSettingsPath = '/api/moryx/factory-monitor/cell-settings/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cellSettings()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  cellSettings$Response(params: CellSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return cellSettings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cellSettings$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  cellSettings(params: CellSettings$Params, context?: HttpContext): Observable<void> {
    return this.cellSettings$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getRoutes()` */
  static readonly GetRoutesPath = '/api/moryx/factory-monitor/routes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRoutes$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoutes$Plain$Response(params?: GetRoutes$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportRouteModel>>> {
    return getRoutes$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRoutes$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoutes$Plain(params?: GetRoutes$Plain$Params, context?: HttpContext): Observable<Array<TransportRouteModel>> {
    return this.getRoutes$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransportRouteModel>>): Array<TransportRouteModel> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRoutes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoutes$Response(params?: GetRoutes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportRouteModel>>> {
    return getRoutes(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRoutes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoutes(params?: GetRoutes$Params, context?: HttpContext): Observable<Array<TransportRouteModel>> {
    return this.getRoutes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransportRouteModel>>): Array<TransportRouteModel> => r.body)
    );
  }

}
