<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Moryx.Model\Moryx.Model.csproj" />
    <ProjectReference Include="..\Moryx\Moryx.csproj" />
    <ProjectReference Include="..\Moryx.Runtime\Moryx.Runtime.csproj" />
    <ProjectReference Include="..\Moryx.Orders\Moryx.Orders.csproj" />
  </ItemGroup>

</Project>
