using System;
using System.Collections.Generic;
using System.Text;
using Marvin.Model;

namespace Marvin.Runtime.UserManagement.Model
{
	/// <summary>
	/// MARVIN Script class to generate indexes for generated tables                                       
	/// This is autogenerated code, therefor any modifications are useless and will be lost on recreation. 
	///                                                                                                    
	/// If you have questions or modification requests contact Thomas Fuchs.                               
	/// </summary>
	internal class UserManagementIndexesScipt : IDatabaseScript
	{
		/// <summary>
		/// Internal class representing a single index
		/// </summary>
		private class Index
		{
			internal Index(string name, string table, string columns)
			{
				Name = name;
				Table = table;
				Columns = columns;
			}

			internal string Name { get; private set; }

			internal string Table { get; private set; }

			internal string Columns { get; private set; }
		}

		public string Name { get { return "UserManagementIndexesScipt"; } }

    public bool IsCreationScript { get { return true; } }

		public string GetText()
		{
			var indexes = GenerateIndexArray();
			return BuildScript(indexes);	
		}

		private IEnumerable<Index> GenerateIndexArray()
		{
			var indexes = new List<Index>
			{
				new Index("IDX_Library_LibraryName", "\"Library\"", "\"LibraryName\""),
				new Index("IDX_UserGroup_GroupName", "\"UserGroup\"", "\"GroupName\""),
				new Index("IDX_Application_ApplicationName", "\"Application\"", "\"ApplicationName\""),
				new Index("IDX_OperationGroup_GroupName", "\"OperationGroup\"", "\"GroupName\""),
				new Index("IDX_Operation_Name", "\"Operation\"", "\"Name\""),
			};
			return indexes;
		}

		private string BuildScript(IEnumerable<Index> indexes)
		{
			var builder = new StringBuilder();
			const string buildString = 
@"CREATE INDEX {0} ON {1} USING btree ({2});";
			foreach (var index in indexes)
			{
				builder.AppendLine(string.Format(buildString, index.Name, index.Table, index.Columns));
			}
			return builder.ToString();
		}
	}
}
