{
 "title": "Notifications Dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "time_interval", "query": "14d" },
   { "name": "severity", "query": "(Warning|Error|Fatal|Info)" },
   { "name": "Title", "query": "New test" },
   { "name": "fromDate", "label": "23/09/2022", "query": "'2022-06-02'" },
   { "name": "toDate", "query": "'2022-10-29'" }
  ]
 },
 "panels": [
  {
   "title": "Date Filter",
   "type": "phoenix-contact-my-plugin",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "phoenix-contact-moryx-notification-severity-checklist",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES  WITH KEY = \"title\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Notifications of a specific Severity",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "SELECT sum(\"duration\") FROM notifications_acknowledged where severity=~/^$severity$/ and time>$fromDate AND time<$toDate GROUP BY time($time_interval),severity fill(0)"
    }
   ]
  },
  {
   "title": "Notifications grouped by Titles",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"id\"), sum(\"duration\") from (select * from notifications_acknowledged where time>$fromDate AND time<$toDate  AND \"severity\"=~ /^$severity$/) group by title, severity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT count(\"id\") as total_count, sum(\"duration\") as total_duration  FROM  (select * from notifications_acknowledged where time>$fromDate AND time<$toDate AND \"severity\"=~ /^$severity$/) "
    }
   ]
  },
  {
   "title": "Notification Title Filter",
   "type": "phoenix-contact-moryx-grafana-notification-title-dropdown",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "SHOW TAG VALUES  WITH KEY = \"title\"  where time>$fromDate AND time<$toDate"
    }
   ]
  },
  {
   "title": "All Notifications of a specific Title",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT * FROM notifications_acknowledged where title=~/^$Title$/ and time>$fromDate AND time<$toDate"
    }
   ]
  }
 ]
}