<Project Sdk="Microsoft.NET.Sdk.Razor" InitialTargets="BuildUI">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="components\**" />
    <Content Remove="components\**" />
    <EmbeddedResource Remove="components\**" />
    <None Remove="components\**" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Moryx.Notifications.Endpoints\Moryx.Notifications.Endpoints.csproj" />
    <ProjectReference Include="..\Moryx.Web\Moryx.Web.csproj" />
    <ProjectReference Include="..\Moryx\Moryx.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <Import Project="..\..\.build\WebProjects.props"/>
  <Target Name="BuildUI" Condition="('$(Configuration)'!='Debug' Or !Exists('wwwroot\notifications\main.js') Or !Exists('wwwroot\notifications-bar\main.js')) And ('$(NoBuild)' != 'true') ">
    <Exec WorkingDirectory=".\app\" Command="npm ci" />
    <Exec WorkingDirectory=".\app\" Command="npm run build:prod notifications" />
    <Exec WorkingDirectory=".\app\" Command="npm run build:prod notifications-bar" />
  </Target>

</Project>
