/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkplanNodeModel } from '../../models/workplan-node-model';
import { WorkplanStepRecipe } from '../../models/workplan-step-recipe';

export interface AddStep$Params {
  sessionId: string;
      body?: WorkplanStepRecipe
}

export function addStep(http: HttpClient, rootUrl: string, params: AddStep$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkplanNodeModel>> {
  const rb = new RequestBuilder(rootUrl, addStep.PATH, 'post');
  if (params) {
    rb.path('sessionId', params.sessionId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkplanNodeModel>;
    })
  );
}

addStep.PATH = '/api/moryx/workplans/sessions/{sessionId}/nodes';

