/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidationResultModel } from '../../models/validation-result-model';

export interface ValidateSession$Params {
  sessionId: string;
}

export function validateSession(http: HttpClient, rootUrl: string, params: ValidateSession$Params, context?: HttpContext): Observable<StrictHttpResponse<ValidationResultModel>> {
  const rb = new RequestBuilder(rootUrl, validateSession.PATH, 'get');
  if (params) {
    rb.path('sessionId', params.sessionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ValidationResultModel>;
    })
  );
}

validateSession.PATH = '/api/moryx/workplans/sessions/{sessionId}/validate';
