/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum PartClassification {
  Unknown = 'Unknown',
  Material = 'Material',
  InfoComponent = 'InfoComponent',
  CarrierMaterial = 'CarrierMaterial',
  ScrapMaterial = 'ScrapMaterial',
  BranchMaterial = 'BranchMaterial'
}

