/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationCreationContextModel } from '../../models/operation-creation-context-model';
import { OperationModel } from '../../models/operation-model';

export interface AddOperation$Params {
  sourceId?: string;
      body?: OperationCreationContextModel
}

export function addOperation(http: HttpClient, rootUrl: string, params?: AddOperation$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationModel>> {
  const rb = new RequestBuilder(rootUrl, addOperation.PATH, 'post');
  if (params) {
    rb.query('sourceId', params.sourceId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperationModel>;
    })
  );
}

addOperation.PATH = '/api/moryx/orders';

