/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Entry } from '@moryx/ngx-web-framework/entry-editor';
import { ProductModel } from '../models/product-model';
export interface PartModel {
  id?: number;
  product?: ProductModel;
  properties?: Entry;
}
