/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DatabaseConfigModel } from '../../models/database-config-model';
import { InvocationResponse } from '../../models/invocation-response';

export interface EraseDatabase$Json$Params {
  targetModel: string;
      body?: DatabaseConfigModel
}

export function eraseDatabase$Json(http: HttpClient, rootUrl: string, params: EraseDatabase$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<InvocationResponse>> {
  const rb = new RequestBuilder(rootUrl, eraseDatabase$Json.PATH, 'delete');
  if (params) {
    rb.path('targetModel', params.targetModel, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InvocationResponse>;
    })
  );
}

eraseDatabase$Json.PATH = '/databases/{targetModel}';
