/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResourceModel } from '../models/resource-model';
export interface ResourceReferenceModel {
  name?: string | null;
  targets?: Array<ResourceModel> | null;
}
