/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResourceTypeModel as MoryxAbstractionLayerResourcesEndpointsResourceTypeModel } from '../../models/Moryx/AbstractionLayer/Resources/Endpoints/resource-type-model';

export interface GetTypeTree$Params {
}

export function getTypeTree(http: HttpClient, rootUrl: string, params?: GetTypeTree$Params, context?: HttpContext): Observable<StrictHttpResponse<MoryxAbstractionLayerResourcesEndpointsResourceTypeModel>> {
  const rb = new RequestBuilder(rootUrl, getTypeTree.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MoryxAbstractionLayerResourcesEndpointsResourceTypeModel>;
    })
  );
}

getTypeTree.PATH = '/api/moryx/resources/types';
