//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the Marvin template for generating a DbContext and Entities. 
// If you have any questions or suggestions for improvement regarding this code, contact Thomas Fuchs. I allways need feedback to improve.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Linq;
using Marvin.Model;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace Marvin.Products.Model
{

    /// <summary>
    /// There are no comments for Marvin.Products.Model.ProductDocument in the schema.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [System.Runtime.Serialization.KnownType(typeof(ProductEntity))]
    public partial class ProductDocument : IEquatable<ProductDocument>, IMergeParent, IModificationTrackedEntity    {
        /// <summary>
        /// Default constructor
        /// </summary>
        public ProductDocument()
        {
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual long Id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private long _id;

    
        /// <summary>
        /// There are no comments for Created in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.DateTime Created
        {
            get
            {
                return _created;
            }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private global::System.DateTime _created;

    
        /// <summary>
        /// There are no comments for Updated in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.DateTime Updated
        {
            get
            {
                return _updated;
            }
            set
            {
                if (_updated != value)
                {
                    _updated = value;
                    OnPropertyChanged("Updated");
                }
            }
        }
        private global::System.DateTime _updated;

    
        /// <summary>
        /// There are no comments for Deleted in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<System.DateTime> Deleted
        {
            get
            {
                return _deleted;
            }
            set
            {
                if (_deleted != value)
                {
                    _deleted = value;
                    OnPropertyChanged("Deleted");
                }
            }
        }
        private global::System.Nullable<System.DateTime> _deleted;

    
        /// <summary>
        /// There are no comments for FileName in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string FileName
        {
            get
            {
                return _fileName;
            }
            set
            {
                if (_fileName != value)
                {
                    _fileName = value;
                    OnPropertyChanged("FileName");
                }
            }
        }
        private string _fileName;

    
        /// <summary>
        /// There are no comments for FilesystemPath in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string FilesystemPath
        {
            get
            {
                return _filesystemPath;
            }
            set
            {
                if (_filesystemPath != value)
                {
                    _filesystemPath = value;
                    OnPropertyChanged("FilesystemPath");
                }
            }
        }
        private string _filesystemPath;

    
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual byte[] File
        {
            get
            {
                return _file;
            }
            set
            {
                if (!StructuralComparisons.StructuralEqualityComparer.Equals(_file, value))
                {
                    _file = value;
                    OnPropertyChanged("File");
                }
            }
        }
        private byte[] _file;

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual int Version
        {
            get
            {
                return _version;
            }
            set
            {
                if (_version != value)
                {
                    _version = value;
                    OnPropertyChanged("Version");
                }
            }
        }
        private int _version = 1;

    
        /// <summary>
        /// There are no comments for Hash in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Hash
        {
            get
            {
                return _hash;
            }
            set
            {
                if (_hash != value)
                {
                    _hash = value;
                    OnPropertyChanged("Hash");
                }
            }
        }
        private string _hash;

    
        /// <summary>
        /// There are no comments for ProductId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual long ProductId
        {
            get
            {
                return _productId;
            }
            set
            {
                if (_productId != value)
                {
                    _productId = value;
                    OnPropertyChanged("ProductId");
                }
            }
        }
        private long _productId;


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual ProductEntity Product
        {
            get;
            set;
        }

        #endregion
        #region IEquatable
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="other">The object to compare with the current object.</param>
        /// <returns><c>true</c> if the specified object is equal to the current object; otherwise, <c>false</c>.</returns>
        public override bool Equals(object other)
        {
            return Equals(other as ProductDocument); 
        }

        /// <summary>
        /// Serves as a hash function for a particular type.
        /// </summary>
        /// <returns>A hash code for the current object.</returns>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="other">The ProductDocument to compare with the current ProductDocument.</param>
        /// <returns><c>true</c> if the specified ProductDocument is equal to the current ProductDocument; otherwise, <c>false</c>.</returns>
        public bool Equals(ProductDocument other)
        {
            if((object)other == null)
                return false;
            
            // First look for Id, then compare references
            return (Id != 0 && Id == other.Id) || object.ReferenceEquals(this, other);
        }
     
        /// <summary>
        /// Compares two ProductDocument objects.
        /// </summary>
        /// <param name="a">The first ProductDocument to compare</param>
        /// <param name="b">The second ProductDocument to compare</param>
        /// <returns><c>true</c> if the specified objects are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(ProductDocument  a, ProductDocument  b)
        {
            if((object)a == null && (object)b == null)
                return true;
            return (object)a != null && a.Equals(b);
        }

        /// <summary>
        /// Compares two ProductDocument objects.
        /// </summary>
        /// <param name="a">The first ProductDocument to compare</param>
        /// <param name="b">The second ProductDocument to compare</param>
        /// <returns><c>true</c> if the specified objects are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(ProductDocument  a, ProductDocument b)
        {
            return !(a == b);
        }

        #endregion
        
        /// <summary>
        /// Reference to merged child
        /// </summary>
        object IMergeParent.Child { get; set; }
    
        #region INotifyPropertyChanged Members

        /// <summary>
        /// Raised when a property value changed.
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises a PropertyChanged event.
        /// </summary>
        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
