//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the Marvin template for generating a DbContext and Entities. 
// If you have any questions or suggestions for improvement regarding this code, contact Thomas Fuchs. I allways need feedback to improve.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Linq;
using Marvin.Model;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace Marvin.Products.Model
{

    /// <summary>
    /// There are no comments for Marvin.Products.Model.StepEntity in the schema.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [System.Runtime.Serialization.KnownType(typeof(WorkplanEntity))]
    [System.Runtime.Serialization.KnownType(typeof(ConnectorReference))]
    [System.Runtime.Serialization.KnownType(typeof(OutputDescriptionEntity))]
    public partial class StepEntity : IEquatable<StepEntity>, IMergeParent, IModificationTrackedEntity    {
        /// <summary>
        /// Default constructor
        /// </summary>
        public StepEntity()
        {
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual long Id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private long _id;

    
        /// <summary>
        /// There are no comments for StepId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual long StepId
        {
            get
            {
                return _stepId;
            }
            set
            {
                if (_stepId != value)
                {
                    _stepId = value;
                    OnPropertyChanged("StepId");
                }
            }
        }
        private long _stepId;

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;

    
        /// <summary>
        /// There are no comments for Assembly in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Assembly
        {
            get
            {
                return _assembly;
            }
            set
            {
                if (_assembly != value)
                {
                    _assembly = value;
                    OnPropertyChanged("Assembly");
                }
            }
        }
        private string _assembly;

    
        /// <summary>
        /// There are no comments for NameSpace in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string NameSpace
        {
            get
            {
                return _nameSpace;
            }
            set
            {
                if (_nameSpace != value)
                {
                    _nameSpace = value;
                    OnPropertyChanged("NameSpace");
                }
            }
        }
        private string _nameSpace;

    
        /// <summary>
        /// There are no comments for Classname in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Classname
        {
            get
            {
                return _classname;
            }
            set
            {
                if (_classname != value)
                {
                    _classname = value;
                    OnPropertyChanged("Classname");
                }
            }
        }
        private string _classname;

    
        /// <summary>
        /// There are no comments for Parameters in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual string Parameters
        {
            get
            {
                return _parameters;
            }
            set
            {
                if (_parameters != value)
                {
                    _parameters = value;
                    OnPropertyChanged("Parameters");
                }
            }
        }
        private string _parameters;

    
        /// <summary>
        /// There are no comments for WorkplanId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual long WorkplanId
        {
            get
            {
                return _workplanId;
            }
            set
            {
                if (_workplanId != value)
                {
                    _workplanId = value;
                    OnPropertyChanged("WorkplanId");
                }
            }
        }
        private long _workplanId;

    
        /// <summary>
        /// There are no comments for SubWorkplanId in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<long> SubWorkplanId
        {
            get
            {
                return _subWorkplanId;
            }
            set
            {
                if (_subWorkplanId != value)
                {
                    _subWorkplanId = value;
                    OnPropertyChanged("SubWorkplanId");
                }
            }
        }
        private global::System.Nullable<long> _subWorkplanId;

    
        /// <summary>
        /// There are no comments for Created in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.DateTime Created
        {
            get
            {
                return _created;
            }
            set
            {
                if (_created != value)
                {
                    _created = value;
                    OnPropertyChanged("Created");
                }
            }
        }
        private global::System.DateTime _created;

    
        /// <summary>
        /// There are no comments for Updated in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.DateTime Updated
        {
            get
            {
                return _updated;
            }
            set
            {
                if (_updated != value)
                {
                    _updated = value;
                    OnPropertyChanged("Updated");
                }
            }
        }
        private global::System.DateTime _updated;

    
        /// <summary>
        /// There are no comments for Deleted in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual global::System.Nullable<System.DateTime> Deleted
        {
            get
            {
                return _deleted;
            }
            set
            {
                if (_deleted != value)
                {
                    _deleted = value;
                    OnPropertyChanged("Deleted");
                }
            }
        }
        private global::System.Nullable<System.DateTime> _deleted;


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Workplan in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual WorkplanEntity Workplan
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for SubWorkplan in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual WorkplanEntity SubWorkplan
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Connectors in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual ICollection<ConnectorReference> Connectors
        {
		    get; set;
        }
    
        /// <summary>
        /// There are no comments for OutputDescriptions in the schema.
        /// </summary>
        [System.Runtime.Serialization.DataMember]
        public virtual ICollection<OutputDescriptionEntity> OutputDescriptions
        {
		    get; set;
        }

        #endregion
        #region IEquatable
        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="other">The object to compare with the current object.</param>
        /// <returns><c>true</c> if the specified object is equal to the current object; otherwise, <c>false</c>.</returns>
        public override bool Equals(object other)
        {
            return Equals(other as StepEntity); 
        }

        /// <summary>
        /// Serves as a hash function for a particular type.
        /// </summary>
        /// <returns>A hash code for the current object.</returns>
        public override int GetHashCode()
        {
            return base.GetHashCode();
        }

        /// <summary>
        /// Determines whether the specified object is equal to the current object.
        /// </summary>
        /// <param name="other">The StepEntity to compare with the current StepEntity.</param>
        /// <returns><c>true</c> if the specified StepEntity is equal to the current StepEntity; otherwise, <c>false</c>.</returns>
        public bool Equals(StepEntity other)
        {
            if((object)other == null)
                return false;
            
            // First look for Id, then compare references
            return (Id != 0 && Id == other.Id) || object.ReferenceEquals(this, other);
        }
     
        /// <summary>
        /// Compares two StepEntity objects.
        /// </summary>
        /// <param name="a">The first StepEntity to compare</param>
        /// <param name="b">The second StepEntity to compare</param>
        /// <returns><c>true</c> if the specified objects are equal; otherwise, <c>false</c>.</returns>
        public static bool operator ==(StepEntity  a, StepEntity  b)
        {
            if((object)a == null && (object)b == null)
                return true;
            return (object)a != null && a.Equals(b);
        }

        /// <summary>
        /// Compares two StepEntity objects.
        /// </summary>
        /// <param name="a">The first StepEntity to compare</param>
        /// <param name="b">The second StepEntity to compare</param>
        /// <returns><c>true</c> if the specified objects are not equal; otherwise, <c>false</c>.</returns>
        public static bool operator !=(StepEntity  a, StepEntity b)
        {
            return !(a == b);
        }

        #endregion
        
        /// <summary>
        /// Reference to merged child
        /// </summary>
        object IMergeParent.Child { get; set; }
    
        #region INotifyPropertyChanged Members

        /// <summary>
        /// Raised when a property value changed.
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises a PropertyChanged event.
        /// </summary>
        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
