//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the Marvin template for generating Repositories and a Unit of Work for Entity Framework model.
// If you have any questions or suggestions for improvement regarding this code, contact Thomas Fuchs.
// Code is generated on: 25.09.2013 15:01:35
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;

namespace Marvin.Model
{
    /// <summary>
    /// Unit of work for db access
    /// </summary>
    public interface IUnitOfWork : IDisposable
    {
        /// <summary>
        /// Namespace of embedded model
        /// </summary>
        string ModelNamespace { get; }
        /// <summary>
        /// Call to internal container for repo implementation
        /// </summary>
        /// <typeparam name="T">Type of repo</typeparam>
        /// <returns></returns>
        T GetRepository<T>() where T : class, IRepository;

        /// <summary>
        /// Get or set the current mode
        /// </summary>
        ContextMode Mode { get; set; }

        /// <summary>
        /// Save all changes
        /// </summary>
        void Save();
    }
}
