name: SBOM Evaluation

on:
  workflow_dispatch:

  push:
    branches:
      - feature/SBOM-evaluation

jobs:
  frontend-sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install CycloneDX NPM
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Verify installation
        run: cyclonedx-npm --version

      - name: Create output directory
        run: mkdir sboms

      - name: Generate SBOMs for all UI projects
        shell: bash
        run: |
          while IFS= read -r lockfile
          do
            dir=$(dirname "$lockfile")
            project=$(basename "$(dirname "$dir")")

            echo "Generating SBOM for $project"

            (
              cd "$dir"

              cyclonedx-npm \
                --output-file "/tmp/${project}.json"
            )

            cp "/tmp/${project}.json" \
              "sboms/${project}-bom.json"

          done < <(find . -name package-lock.json)

      - name: Show generated files
        run: ls -lah sboms

      - name: Upload frontend SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: frontend-sboms
          path: sboms/*.json
