name: SBOM Evaluation

on:
  workflow_dispatch:

  push:
    branches:
      - feature/SBOM-evaluation

jobs:
  frontend-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install CycloneDX NPM
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Verify installation
        run: cyclonedx-npm --version

      - name: Create output directory
        run: mkdir -p sboms

      - name: Generate frontend SBOMs
        shell: bash
        run: |
          mkdir -p sboms

          for lockfile in $(find . -name package-lock.json)
          do
            dir=$(dirname "$lockfile")
            project=$(basename "$(dirname "$dir"))

            echo "Processing $project"

            pushd "$dir"

            npm ci

            cyclonedx-npm --output-file "${RUNNER_TEMP}/${project}.json"

            popd

            cp "${RUNNER_TEMP}/${project}.json" "sboms/${project}-bom.json"
          done
          
      - name: Show generated SBOMs
        run: |
          ls -lah sboms

      - name: Upload frontend SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: frontend-sboms
          path: sboms/*.json
