/*
 * Copyright (c) 2026 Phoenix Contact GmbH & Co. KG
 * Licensed under the Apache License, Version 2.0
*/

/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportRouteModel } from '../../models/transport-route-model';

export interface GetRoutes$Json$Params {
}

export function getRoutes$Json(http: HttpClient, rootUrl: string, params?: GetRoutes$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportRouteModel>>> {
  const rb = new RequestBuilder(rootUrl, getRoutes$Json.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransportRouteModel>>;
    })
  );
}

getRoutes$Json.PATH = '/api/moryx/factory-monitor/routes';
